---
galaxy_info:
  author: Roderik van der Veer
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
#  - mkheriwala.superlumic-computername
#  - mkheriwala.superlumic-cli
#  - mkheriwala.superlumic-homebrew
#  - mkheriwala.superlumic-mysql
#  - mkheriwala.superlumic-php
  - mkheriwala.superlumic-sublimetext
#  - mkheriwala.superlumic-skylab
  - mkheriwala.superlumic-node
  - mkheriwala.superlumic-vim
  - profile-all
