---

#- src: https://github.com/superlumic/ansible-role-homebrew.git
#  name: mkheriwala.superlumic-homebrew
#
#- src: https://github.com/superlumic/ansible-role-osx-defaults.git
#  name: mkheriwala.superlumic-osx-defaults

#- src: https://github.com/superlumic/ansible-role-computername.git
#  name: mkheriwala.superlumic-computername

#- src: https://github.com/superlumic/ansible-role-cli.git
#  name: mkheriwala.superlumic-cli

#- src: https://github.com/superlumic/ansible-role-mysql.git
#  name: mkheriwala.superlumic-mysql
#
#- src: https://github.com/superlumic/ansible-role-php.git
#  name: mkheriwala.superlumic-php

- src: https://github.com/superlumic/ansible-role-sublimetext.git
  name: mkheriwala.superlumic-sublimetext

- src: https://github.com/superlumic/ansible-role-node.git
  name: mkheriwala.superlumic-node

- src: https://github.com/superlumic/ansible-role-postgresql.git
  name: mkheriwala.superlumic-postgresql

- src: https://github.com/superlumic/ansible-role-vim.git
  name: mkheriwala.superlumic-vim

#- src: https://github.com/superlumic/ansible-role-modjk.git
#  name: mkheriwala.superlumic-modjk

#- src: https://github.com/superlumic/ansible-role-skylab.git
#  name: mkheriwala.superlumic-skylab
